---
abstract: unknown
author:
  - 'Dan Brook <cpan@broquaint.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Locate
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  File::Spec::Functions: 0
  IO::File: 0
  overload: 0
  strict: 0
resources:
  repository: https://github.com/neilbowers/Module-Locate
version: 1.73
